routes/web.php
<?php

use App\Models\Product;
use App\Http\Controllers\ProductController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('products');
// });

Route::get('/', [ProductController::class, 'index']);
Route::resource('products', ProductController::class);

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;

    protected $table = 'products';

    protected $fillable = ['descripcion', 'precio'];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;
use App\Models\Product;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('products', [
            'products' => Product::all()
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $product = new Product;
        $product->descripcion = $request->descripcion;
        $product->precio = $request->precio;

        $product->save();

        return redirect('/products');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = Product::find($id);

        return view('edit', compact('product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $product = Product::find($id);

        $product->descripcion = $request->descripcion;
        $product->precio = $request->precio;

        $product->save();

        return redirect('/products');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $product = Product::where('id', $id);

        $product->delete();

        return redirect('/products');
    }
}

resources/views/create.blade.php
<form method="post" action="{{ route('products.store') }}">  
   @csrf     
          <div class="form-group">      
              <label for="descripcion">Descripcion:</label><br/><br/>  
              <input type="text" class="form-control" name="descripcion"/><br/><br/>  
          </div>  
<div class="form-group">      
<label for="precio">Precio:</label><br/><br/>  
              <input type="number" step=0.01 class="form-control" name="precio"/><br/><br/>  
          </div>  
<br/>  
<button type="submit" class="btn-btn">Insert</button>
</form>  

resources/views/edit.blade.php
<form method="post" action="{{ route('products.update', $product->id) }}">  
   @csrf
   @method('PATCH')     
          <div class="form-group">      
              <label for="descripcion">Descripcion:</label><br/><br/>  
              <input type="text" class="form-control" name="descripcion" value="{{ $product->descripcion }}"/><br/><br/>  
          </div>  
<div class="form-group">      
<label for="precio">Precio:</label><br/><br/>  
              <input type="number" step=0.01 class="form-control" name="precio" value="{{ $product->precio }}"/><br/><br/>  
          </div>  
<br/>  
<button type="submit" class="btn-btn">Modificar</button>
</form>  

resources/views/products.blade.php
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Crud Productos</title>

  <!-- Styles -->
  <link href={{ url('css/bootstrap.min.css') }} rel="stylesheet">
  <link href={{ url('css/datatables.min.css') }} rel="stylesheet">

  <!-- Scripts -->
  <script src={{ url('js/jquery-3.6.0.min.js') }}></script>
  <script src={{ url('js/popper.min.js') }}></script>
  <script src={{ url('js/bootstrap.min.js') }}></script>
  <script src={{ url('js/datatables.min.js') }}></script>
</head>
<body>
  <div class="container mt-5">
    <div class="row">
      <div class="col-12">
        <table class="table table-striped table-bordered table-hover" id="tablaarticulos">
          <thead>
            <tr style="font-weight: bold;">
              <td>Código</td>
              <td>Descripción</td>
              <td>Precio</td>
              <td>Modificar</td>
              <td>Borrar</td>
            </tr>
          </thead>
          <tbody>
            @foreach ($products as $product)
            <tr>
              <th>{{ $product->id }}</th>
              <td>{{ $product->descripcion }}</td>
              <td>{{ $product->precio }}</td>
              <td>
                <a href="{{ route('products.edit', $product->id) }}">
                  <button class="btn btn-warning">Editar</button>
                </a>
              </td>
              <td>
                  <form action="{{ route('products.destroy', $product->id) }}" method="post">
                    @csrf
                    @method('DELETE')
                    <button type="submit" class="btn btn-danger">Eliminar</button>
                  </form>
              </td>
            </tr>
            @endforeach
          </tbody>
        </table>
        <a href="{{ route('products.create') }}">
          <button class="btn btn-sm btn-primary" id="BotonAgregar">Agregar artículo</button>
        </a>
      </div>
    </div>
  
    <!-- Formulario (Agregar, Modificar) -->
    <!-- <div class="modal fade" id="FormularioArticulo" tabindex="-1" role="dialog">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">
              <span aria-hidden="true">×</span>
            </button>
          </div>
          <div class="modal-body">
            <input type="hidden" id="Codigo">
            <div class="form-row">
              <div class="form-group col-md-12">
                <label>Descripción:</label>
                <input type="text" id="Descripcion" class="form-control" placeholder="">
              </div>
            </div>
            <div class="form-row">
              <div class="form-group col-md-12">
                <label>Precio:</label>
                <input type="number" id="Precio" class="form-control" placeholder="">
              </div>
            </div>
            <div class="modal-footer">
              <button type="button" id="ConfirmarAgregar" class="btn btn-success">Agregar</button>
              <button type="button" id="ConfirmarModificar" class="btn btn-info">Modificar</button>
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
            </div>
          </div>
        </div>
      </div>
    </div> -->
  </div>
</body>
</html>